name: Build and Push and Deploy Docker Image

on:
  workflow_dispatch: 
jobs:
  build-and-push-frontend:
     name: Build and Push Frontend Image
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3

       - name: Set up Docker
         uses: docker/setup-buildx-action@v3

       - name: Login to DockerHub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build and Push Frontend
         uses: docker/build-push-action@v5
         with:
           context: ./note-frontend
           push: true
           tags: lfortest/note-frontend:latest
  
  deploy-to-gcp:
    name: Deploy to GCP VM
    runs-on: ubuntu-latest
    needs: build-and-push-frontend
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Deploy on GCP VM via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            docker pull lfortest/note-frontend:latest
            docker stop note-frontend || true
            docker rm note-frontend || true
            docker run -d --name note-frontend -p 80:3000 lfortest/note-frontend:latest
            docker image prune -f
          EOF
